### ISSUE TITLE
Error 0:-8 Conversation not found

### ISSUE THREAD

**Issue by aslamhossin** [twilio/twilio-conversations-demo-kotlin#18]
Getting this error getting conversation after building ConversationClient successfully build. 

D/TWC:    3 | Twilsock Client | sendRequestImpl in state Connected 
     Method: GET
     requestId: RQ745e2f506dab4acea9662431a5347e76
     Host: aim.us1.twilio.com
     Path: /v1/Instances/IS0b7d9ed5e5454b34b637f1352dfcec95/Users/US9d09f5310e7f4e74a8993c2180aea762/SyncList

**Comment by rusmonster** [comment]
Hello!
Please provide the full log

**Comment by berkus** [comment]
@aslamhossin hi, could you please provide a detailed log or confirm this is no longer a problem for you? Thanks.

**Comment by aslamhossin** [comment]
It's hardly possible to share the log cause has some restriction.

**Comment by berkus** [comment]
It seems that you are trying to query a PUBLIC channel type. Conversations does not support public channels and those will be filtered out, hence the error you're getting.

Without more details I cannot be more specific, sorry.
