### ISSUE TITLE
Build failed after adding the java helper library

### ISSUE THREAD

**Issue by amiteshsinghkundan** [twilio/twilio-conversations-demo-kotlin#32]
In this demo project users were always shows offline whether he is online. According to the document, https://www.twilio.com/docs/conversations/api/service-configuration-resource,
we need to Install the Java helper library from 
twilio.com/docs/java/install
After Adding =>
implementation group: "com.twilio.sdk", name: "twilio", version: "8.26.0" 
in build .gradle.  Build failed "Caused by: org.gradle.workers.internal.DefaultWorkerExecutor$WorkExecutionException: A failure occurred while executing com.android.build.gradle.internal.tasks.CheckDuplicatesRunnable"
![image](https://user-images.githubusercontent.com/97089194/155091899-cec257fb-989d-4cfb-b2a3-8ea3ebfb8e0e.png)

**Comment by rusmonster** [comment]
Hello @amiteshsinghkundan !

In order to get notifications about users reachability (online/offline) on SDK side you don't need any helper libraries, instead you need to enable the `reachability` feature for your service instance in the twilio console (the feature is disabled by default).

How to enable reachability:
1. Login into twilio console
2. Go to Explore Products -> Chat -> Manage -> Services -> $YOUR_SERVICE -> Base Configuration. 
3. Select the `reachability enabled` checkbox

Let me know if it works for you?

**Comment by amiteshsinghkundan** [comment]
Hi @rusmonster Thak you so much it worked. Now  its showing that users is online and offline but its not updating status in the real time. 
1)Users1 have to close the bottomSheet and swiperefresh the participant list than its updating the status the user2 status. if User 2 haven't open the app it shows offline
2) if user2 open the app and put the app in the background by clicking the home button, User1 get the status that User2 is online even after refreshing the layout.
Is there any listener for online offline status?

**Comment by rusmonster** [comment]
Hi @amiteshsinghkundan sorry for the delay!

There is the `onUserUpdated` callback in `ConversationsClientListener` which receives updates about reachability changes for users which are subscribed for updates. This app doesn't listen it at the moment.

When user2 puts the app into background - his/her reachability doesn't change. user2 will go offline when SDK really lost a connection, which happens, for instance, in the following cases:
- device lost internet connection
- app process has been killed in background by android OS
- app calls `ConversationsClient.shutdown()`

**Comment by amiteshsinghkundan** [comment]
Thank you so much its working.
