### ISSUE TITLE
Send  custom notification

### ISSUE THREAD

**Issue by amiteshsinghkundan** [twilio/twilio-conversations-demo-kotlin#38]
Sdk has inbuilt push notification through which we can send push notification for new messages, user added in a conversation, user removed from conversation. These are working.  According to the requirement of our app we need to send some custom notification to all the users in a conversation. 
1. How we can send the custom notification?
i have gone through the below link but not able to send the custom notification
https://www.twilio.com/docs/notify/register-for-notifications-android

**Comment by SagarWithShareCare** [comment]
We have the same issue. We have gone through:

https://www.twilio.com/docs/conversations/android/push-notifications

And found that:

<img width="644" alt="image" src="https://user-images.githubusercontent.com/100230029/163539081-2a427342-4233-45b1-b149-2dd6ef6b40d0.png">

We could not find a way to send custom push notifications for specific events such as when a user comes online, or when a user goes offline, disables (removes access), or enables (grants certain permissions) a particular user, and there can be many more custom events based on an application.

There can be many events not connected with Twilio, or not using Twilio SDK or Twilio API in any way but we may need Twilio to be able to send and receive notifications for these events.

For example, we are using Twilio Conversations SDK for Android, we have a user profile section that includes an address, and we want to send a push notification to all the participants when a particular user changes the address.

We have already gone through:
https://www.twilio.com/docs/conversations/push-notification-configuration 

But could not find a way to achieve that using Twilio SDK.

**Comment by networkinterfacecontroller** [comment]
Hi! Conversations built-in pushes don't support adding additional push notification types. However, you can use Twilio Notify (twilio.com/docs/notify) alongside the post-action webhooks (https://www.twilio.com/docs/conversations/conversations-webhooks#post-action-webhooks) to send pushes for any custom event you'd like. Hope this helps!
